### ISSUE TITLE
Chrome "contribute!" seems not to work

### ISSUE THREAD

**Issue by m-o-p** [vcharpenay/web-nav-window#6]
Chrome on Mac OSX Catalina.
I clicked anonymize. Then "contribute!". I get this:
<img width="433" alt="Screenshot 2021-05-13 at 20 22 46" src="https://user-images.githubusercontent.com/7588878/118169322-1b52c480-b429-11eb-9275-8010e45b96bb.png">

**Comment by vcharpenay** [comment]
Were you using that browser in March 2020? I've heard quite a few people telling me they had changed PC/browser since then.

**Comment by m-o-p** [comment]
You are right, I did not read the text and assumed my contribution would be from the data visualized. In fact I lost my computer that I had used in that period... Therefore it is clear. Thanks!
